# Generated by Django 4.0.6 on 2022-08-01 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CollegeApp', '0003_usermember'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdcrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('course_name', models.CharField(max_length=100)),
                ('course_fee', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
