# Generated by Django 4.0.6 on 2022-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0004_stdcrs_alter_usermember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=100)),
                ('user_contact', models.IntegerField()),
                ('user_image', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
