# Generated by Django 4.0.6 on 2022-08-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0005_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
