# Generated by Django 4.0.6 on 2022-08-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0006_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='user_course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.course'),
        ),
    ]
