# Generated by Django 4.0.6 on 2022-08-02 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CollegeApp', '0008_alter_usermember_user_alter_usermember_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_image',
            field=models.ImageField(blank=True, default='images/dp.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_image',
            field=models.ImageField(blank=True, default='images/dp.png', upload_to='images/'),
        ),
    ]
